### ISSUE TITLE
CombinatorialValues(null) breaks generation of combinations

### ISSUE THREAD

**Issue by 0x00FC** [AArnott/Xunit.Combinatorial#20]
Hello
I'm very happy with this package, but I found a bug.
This code does not produce a combination of 3 tests as expected:

```cs
[Theory]
[CombinatorialData]
public void CombinatorialBug(
   [CombinatorialValues(1, 2, 3)] int paramA,
   [CombinatorialValues(null)] string paramB)
{ }
```

while this works correctly

```cs
[Theory]
[CombinatorialData]
public void CombinatorialBug(
   [CombinatorialValues(1, 2, 3)] int paramA,
   [CombinatorialValues("foo")] string paramB)
{ }
```

and this too (6  tests)

```cs
[Theory]
[CombinatorialData]
public void CombinatorialBug(
  [CombinatorialValues(1, 2, 3)] int paramA,
  [CombinatorialValues(null,"foo")] string paramB  )
{ }
```

**Comment by AArnott** [comment]
This isn't a bug in the library. It's a nuance of how C# does `params` attributes. If you pass `null` in for a `params` attribute, instead of turning that into `new object[] { null }`, C# just passes in `null` itself. The attribute rejects a `null` array today because it wants an array of objects. 

So this works fine:

```cs
[Theory]
[CombinatorialData]
public void CombinatorialBug(
   [CombinatorialValues(1, 2, 3)] int paramA,
   [CombinatorialValues(new object[] { null })] string paramB)
{ }
```

That said, we can probably re-interpret a `null` array as an array with a single `null` element to make this easier.
